<?php return array (
    'site_name' => 'LOKALHOST',
    'site_url' => 'http://192.168.0.156',
    'secret' => 'S0m3th1ng r4nd0m',
    'adminer_password' => md5('admin'),
    'database' => 'db/kyselo.sqlite',
    'invitation_code' => ['xyzzy'],
    'show_debug'=>true,
    'hosted_by' => 'underpant gnomes',
    'hosted_by_url' => 'http://example.org',
    'tos_post'=>1,
    'footer_javascript'=>'<script>console.log("external stats  here")</script>',
    'souper_endpoint_key'=>'some_random_string',
    // 'maintance_mode'=>true,
);